name: Proxy Checker

on:
  schedule:
    - cron: '0 * * * *'  # اجرای هر یک ساعت (0 دقیقه از هر ساعت)

jobs:
  run-proxy-checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run proxy checker
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}  # ایمیل فرستنده
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # رمز عبور ایمیل فرستنده
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}  # ایمیل گیرنده
      run: |
        python main.py  # اجرای اسکریپت اصلی با نام main.py
